name: build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [master]

env:
  CXX: clang++

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building the application
        run: make
